import { GalleryItem } from './types';

export const GALLERY_ITEMS: GalleryItem[] = [
    { id: '1', url: "/assets/images/service/OurLogoDesigns/LOGO_1.png", alt: 'Brand Identity 1', spanType: 'medium' },
    { id: '2', url: '/assets/images/service/OurLogoDesigns/LOGO_2.png', alt: 'Digital Solution 1', spanType: 'tall' },
    { id: '3', url: '/assets/images/service/OurLogoDesigns/LOGO_3.png', alt: 'Production 1', spanType: 'small' },
    { id: '4', url: '/assets/images/service/OurLogoDesigns/LOGO_4.png', alt: 'Creative Concept 1', spanType: 'medium' },
    { id: '5', url: '/assets/images/service/OurLogoDesigns/LOGO_5.png', alt: 'Workspace 1', spanType: 'tall' },
    { id: '6', url: '/assets/images/service/OurLogoDesigns/LOGO_6.png', alt: 'Detail 1', spanType: 'small' },
    { id: '7', url: '/assets/images/service/OurLogoDesigns/LOGO_7.png', alt: 'Development 1', spanType: 'medium' },
    { id: '8', url: '/assets/images/service/OurLogoDesigns/LOGO_8.png', alt: 'Structural Design 1', spanType: 'extra-tall' },
    { id: '9', url: '/assets/images/service/OurLogoDesigns/LOGO_9.png', alt: 'Process 1', spanType: 'small' },
    { id: '10', url: '/assets/images/service/OurLogoDesigns/LOGO_10.png', alt: 'Photography 1', spanType: 'medium' },
    { id: '11', url: '/assets/images/service/OurLogoDesigns/LOGO_11.png', alt: 'Creative View 1', spanType: 'wide' },
    { id: '12', url: '/assets/images/service/OurLogoDesigns/LOGO_12.png', alt: 'Style Guide 1', spanType: 'tall' },
    { id: '13', url: '/assets/images/service/OurLogoDesigns/LOGO_13.png', alt: 'Space 1', spanType: 'small' },
    { id: '14', url: '/assets/images/service/OurLogoDesigns/LOGO_14.png', alt: 'Vibrant Identity 1', spanType: 'medium' },
    { id: '15', url: '/assets/images/service/OurLogoDesigns/LOGO_15.png', alt: 'Modern Graphics 1', spanType: 'wide' },
    { id: '16', url: '/assets/images/service/OurLogoDesigns/LOGO_16.png', alt: 'Package Design 1', spanType: 'tall' },
    { id: '17', url: '/assets/images/service/OurLogoDesigns/LOGO_17.png', alt: 'Type System 1', spanType: 'small' },
    { id: '18', url: '/assets/images/service/OurLogoDesigns/LOGO_18.png', alt: 'Signage 1', spanType: 'medium' },
    { id: '19', url: '/assets/images/service/OurLogoDesigns/LOGO_19.png', alt: 'Campaign 1', spanType: 'wide' },
    { id: '20', url: '/assets/images/service/OurLogoDesigns/LOGO_20.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
    { id: '21', url: '/assets/images/service/OurLogoDesigns/LOGO_21.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
    { id: '22', url: '/assets/images/service/OurLogoDesigns/LOGO_22.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
    { id: '23', url: '/assets/images/service/OurLogoDesigns/LOGO_23.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
    { id: '24', url: '/assets/images/service/OurLogoDesigns/LOGO_24.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
    { id: '25', url: '/assets/images/service/OurLogoDesigns/LOGO_25.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
    { id: '26', url: '/assets/images/service/OurLogoDesigns/LOGO_26.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
    { id: '27', url: '/assets/images/service/OurLogoDesigns/LOGO_27.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
    { id: '28', url: '/assets/images/service/OurLogoDesigns/LOGO_28.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
    { id: '29', url: '/assets/images/service/OurLogoDesigns/LOGO_29.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
    { id: '30', url: '/assets/images/service/OurLogoDesigns/LOGO_30.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
    { id: '31', url: '/assets/images/service/OurLogoDesigns/LOGO_31.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
    { id: '32', url: '/assets/images/service/OurLogoDesigns/LOGO_32.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
    { id: '33', url: '/assets/images/service/OurLogoDesigns/LOGO_33.png', alt: 'Creative Pluz Studio', spanType: 'extra-tall' },
];

export const SPAN_MAP = {
    'small': 'row-span-1 col-span-1',
    'medium': 'row-span-2 col-span-2',
    'tall': 'row-span-3 col-span-2',
    'extra-tall': 'row-span-4 col-span-2',
    'wide': 'row-span-1 col-span-2',
};
